server:
  port: 8900

eureka:
  client:
    serviceUrl:
      defaultZone: ${APP.SERVER.URL}:8761/eureka/
  instance:
    preferIpAddress: true

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
              - PATCH
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true
      routes:
        - id: gateway
          uri: ${APP.SERVER.URL}:8900
          predicates:
            - Path=/gateway/**
          filters:
            - RewritePath=/gateway/(?<path>.*), /$\{path}
        - id: user
          uri: ${APP.SERVER.URL}:8200
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=^/user/(?<path>.*), /api/v1/$\{path}