server:
  port: 8900

eureka:
  client:
    serviceUrl:
      defaultZone: ${APP.SERVER.URL}:8761/eureka/
  instance:
    preferIpAddress: true

spring:

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
              - PATCH
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true
      routes:
        - id: gateway
          uri: ${APP.SERVER.URL}:8900
          predicates:
            - Path=/gateway/**
          filters:
            - RewritePath=/gateway/(?<path>.*), /$\{path}
        - id: user
          uri: ${APP.SERVER.URL}:8200
          predicates:
            - Path=/user/**,/v3/api-docs/user
          filters:
            - RewritePath=^/user/(?<path>.*), /api/v1/$\{path}
        - id: openapi
          uri: ${APP.SERVER.URL}:8900
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        - id: swagger-ui
          uri: ${APP.SERVER.URL}:8900/webjars/springdoc-openapi-ui/index.html
          predicates:
            - Path=/swagger-ui/**
          filters:
            - RewritePath=/swagger-ui/(?<path>.*), /$\{path}


springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /v3/api-docs/user
        name: User Service
        primaryName: User Service